# Generated by Django 5.2.15 on 2026-06-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpublish',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Toggling this off hides the section on the live homepage'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(help_text='Unique identifier for this setting', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='value',
            field=models.TextField(blank=True, help_text='The value for this setting'),
        ),
    ]
