# Generated by Django 5.2.15 on 2026-06-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'X (Twitter)'), ('yelp', 'Yelp'), ('tiktok', 'TikTok'), ('linkedin', 'LinkedIn'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('website', 'Website'), ('other', 'Other')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='business.business')),
            ],
            options={
                'ordering': ['sort_order'],
            },
        ),
    ]
